# cloc rule,

shell script
    filter remove_matches ^\s*#
    filter remove_inline #.*$
    extension sh
    3rd_gen_scale 3.81
    end_of_line_continuation \\$

shell like script
    filter remove_matches ^\s*#
    filter remove_inline #.*$
    extension dsh
    extension bsh
    extension tmx
    extension fsh
    extension swy
    extension dash
    extension bash
    extension tmux
    extension fish
    extension sway
    3rd_gen_scale 3.81
    end_of_line_continuation \\$

linux config
    filter remove_matches ^\s*#
    filter remove_inline #.*$
    extension ini
    extension conf
    extension config
    extension inc
    extension rules
    3rd_gen_scale 3.81
    end_of_line_continuation \\$

lua script
    filter remove_between_general --[=====[ ]=====]
    filter remove_between_general --[====[ ]====]
    filter remove_between_general --[===[ ]===]
    filter remove_between_general --[==[ ]==]
    filter remove_between_general --[=[ ]=]
    filter remove_between_general --[[ ]]
    filter remove_matches ^\s*\-\-
    extension lua
    script_exe lua
    3rd_gen_scale 4.00
    end_of_line_continuation \\$

vim script
    filter remove_matches ^\s*"
    filter remove_inline ".*$
    extension vim
    3rd_gen_scale 3.00

system service
    filter remove_matches ^\s*#
    filter remove_inline #.*$
    extension service
    extension target
    3rd_gen_scale 3.81
    end_of_line_continuation \\$

toml and yaml
    filter remove_matches ^\s*#
    filter remove_inline #.*$
    extension toml
    extension yaml
    3rd_gen_scale 2.76

html and xml
    filter remove_html_comments
    filter call_regexp_common HTML
    extension html
    extension xml
    3rd_gen_scale 1.90

css
    filter rm_comments_in_strings " /* */
    filter rm_comments_in_strings " //
    # filter call_regexp_common c
    extension css
    3rd_gen_scale 1.00

js
    filter rm_comments_in_strings ' /* */
    filter rm_comments_in_strings ' //
    filter rm_comments_in_strings " /* */
    filter rm_comments_in_strings " //
    filter call_regexp_common C++
    extension _js
    extension js
    3rd_gen_scale 1.48
    end_of_line_continuation \\$

json
    filter remove_matches ^\s*$
    extension arcconfig
    extension json
    3rd_gen_scale 2.50

markdown
    filter remove_between_general <!-- -->
    filter remove_between_regex \[(comment|\/\/)?\]\s*:?\s*(<\s*>|#)?\s*\(.*? .*?\)
    extension contents.lr
    extension markdown
    extension md
    3rd_gen_scale 1.00

