# ALACRITTY config, the gpu enhanced terminal emulator.


[general]

import = [

"~/.config/alacritty/basic.toml"  ,
"~/.config/alacritty/window.toml" ,
"~/.config/alacritty/color.toml"  ,

"~/.config/alacritty/key/char.toml" ,
"~/.config/alacritty/key/ctrl.toml" ,

]


