# ALACRITTY config, color


[colors]
  transparent_background_colors = true
  cursor         = { text = "CellBackground", cursor = "CellForeground" }
  vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
  primary        = { foreground = "#e0e0e0",  background = "#202020"  }

[colors.normal]
  red      = "#a08050"
  green    = "#50a080"
  blue     = "#5080a0"
  yellow   = "#8050a0"
  cyan     = "#80a050"
  magenta  = "#a05080"

[colors.bright]
  red      = "#f0c0c0"
  green    = "#c0f0c0"
  blue     = "#c0c0f0"
  yellow   = "#f0f0c0"
  cyan     = "#c0f0f0"
  magenta  = "#f0c0f0"

[colors.dim]
  red      = "#300000"
  green    = "#003000"
  blue     = "#000030"
  yellow   = "#303000"
  cyan     = "#003030"
  magenta  = "#300030"


