# punctuation

keycode  41  =  grave         asciitilde
keycode  12  =  underscore    minus
keycode  13  =  equal         plus

keycode  26  =  bracketleft   braceleft
keycode  27  =  bracketright  braceright
keycode  43  =  backslash     bar

keycode  39  =  semicolon     colon
keycode  40  =  apostrophe    quotedbl

keycode  51  =  comma         less
keycode  52  =  period        greater
keycode  53  =  slash         question


