# function

plain keycode  59 = F1
plain keycode  60 = F2
plain keycode  61 = F3
plain keycode  62 = F4
plain keycode  63 = F5
plain keycode  64 = F6
plain keycode  65 = F7
plain keycode  66 = F8
plain keycode  67 = F9
plain keycode  68 = F10
plain keycode  87 = F11
plain keycode  88 = F12

shift keycode  59 = F13
shift keycode  60 = F14
shift keycode  61 = F15
shift keycode  62 = F16
shift keycode  63 = F17
shift keycode  64 = F18
shift keycode  65 = F19
shift keycode  66 = F20
shift keycode  67 = F21
shift keycode  68 = F22
shift keycode  87 = F23
shift keycode  88 = F24

control keycode  59 = F25
control keycode  60 = F26
control keycode  61 = F27
control keycode  62 = F28
control keycode  63 = F29
control keycode  64 = F30
control keycode  65 = F31
control keycode  66 = F32
control keycode  67 = F33
control keycode  68 = F34
control keycode  87 = F35
control keycode  88 = F36


