# console

alt keycode  59  =  Console_1
alt keycode  60  =  Console_2
alt keycode  61  =  Console_3
alt keycode  62  =  Console_4
alt keycode  63  =  Console_5
alt keycode  64  =  Console_6
alt keycode  65  =  Console_7
alt keycode  66  =  Console_8
alt keycode  67  =  Console_9
alt keycode  68  =  Console_10
alt keycode  87  =  Console_11
alt keycode  88  =  Console_12

control alt keycode  59  =  Console_1
control alt keycode  60  =  Console_2
control alt keycode  61  =  Console_3
control alt keycode  62  =  Console_4
control alt keycode  63  =  Console_5
control alt keycode  64  =  Console_6
control alt keycode  65  =  Console_7
control alt keycode  66  =  Console_8
control alt keycode  67  =  Console_9
control alt keycode  68  =  Console_10
control alt keycode  87  =  Console_11
control alt keycode  88  =  Console_12

control alt keycode 105  =  Decr_Console
control alt keycode 106  =  Incr_Console
