# ctrl

# control keycode  57  =  Meta_at            #  0x00 C+@ C+Space
# control keycode  30  =  Meta_A             #  0x01 C+a
# control keycode  48  =  Meta_B             #  0x02 C+b
# control keycode  46  =  Meta_C             #  0x03 C+c
# control keycode  32  =  Meta_D             #  0x04 C+d
# control keycode  18  =  Meta_E             #  0x05 C+e
# control keycode  33  =  Meta_F             #  0x06 C+f
# control keycode  34  =  Meta_G             #  0x07 C+g
# control keycode  35  =  Meta_H             #  0x08 C+h BackSpace
# control keycode  23  =  Meta_I             #  0x09 C+i Tab
# control keycode  36  =  Meta_J             #  0x0a C+j Linefeed
# control keycode  37  =  Meta_K             #  0x0b C+k
# control keycode  38  =  Meta_L             #  0x0c C+l
control keycode  50  =  Meta_M             #  0x0d C+m Enter
# control keycode  49  =  Meta_N             #  0x0e C+n
# control keycode  24  =  Meta_O             #  0x0f C+o
# control keycode  25  =  Meta_P             #  0x10 C+p
# control keycode  16  =  Meta_Q             #  0x11 C+q
# control keycode  19  =  Meta_R             #  0x12 C+r
# control keycode  31  =  Meta_S             #  0x13 C+s
# control keycode  20  =  Meta_T             #  0x14 C+t
# control keycode  22  =  Meta_U             #  0x15 C+u
# control keycode  47  =  Meta_V             #  0x16 C+v
# control keycode  17  =  Meta_W             #  0x17 C+w
# control keycode  45  =  Meta_X             #  0x18 C+x
# control keycode  21  =  Meta_Y             #  0x19 C+y
# control keycode  44  =  Meta_Z             #  0x1a C+z

# control keycode  41  =  Meta_asciitilde    #  0x7e C+~
# control keycode  12  =  Meta_minus         #  0x5f C+-
# control keycode  13  =  Meta_plus          #  0x2b C++
control keycode  26  =  Meta_braceleft     #  0x7b C+{
control keycode  27  =  Meta_braceright    #  0x7d C+}
# control keycode  43  =  Meta_bar           #  0x7c C+|
control keycode  39  =  Meta_colon         #  0x3a C+:
control keycode  40  =  Meta_quotedbl      #  0x22 C+"
control keycode  51  =  Meta_less          #  0x3c C+<
control keycode  52  =  Meta_greater       #  0x3e C+>
# control keycode  53  =  Meta_question      #  0x3f C+?

control keycode   1  =  Meta_Escape

