# override

control	keycode 15 = F121
control	keycode  1 = F122
control	keycode 28 = F123

control	keycode 50 = F131

control	keycode 12 = F111
control	keycode 13 = F112
control	keycode 26 = F113
control	keycode 27 = F114
control	keycode 39 = F115
control	keycode 40 = F116
control	keycode 51 = F117
control	keycode 52 = F118
control	keycode 43 = F119
control	keycode 53 = F120
control	keycode 41 = F140

control	keycode 2  = F101
control	keycode 3  = F102
control	keycode 4  = F103
control	keycode 5  = F104
control	keycode 6  = F105
control	keycode 7  = F106
control	keycode 8  = F107
control	keycode 9  = F108
control	keycode 10 = F109
control	keycode 11 = F110


string F121        = "Ñ"
string F122        = "Ò"
string F123        = "Ü"

string F131        = "Ú"

string F111        = "á"
string F112        = "â"
string F113        = "ã"
string F114        = "ä"
string F115        = "å"
string F116        = "æ"
string F117        = "ç"
string F118        = "è"
string F119        = "é"
string F120        = "ê"
string F140        = "ë"

string F101        = "ñ"
string F102        = "ò"
string F103        = "ó"
string F104        = "ô"
string F105        = "õ"
string F106        = "ö"
string F107        = "÷"
string F108        = "ø"
string F109        = "ù"
string F110        = "ú"


