# TMUX config, terminal multiplexer.


%hidden config="$HOME/.config/tmux"
source $config/basic.tmx
# source $config/hook.tmx

%hidden keymap="$HOME/.config/tmux/keymap"
# source $keymap/tmux.tmx
# source $keymap/unpref.tmx
# source $keymap/unctrl.tmx
source $keymap/ctrl.tmx
source $keymap/pref.tmx
source $keymap/copy.tmx

# source ~/.config/tmux/plugins/misty.tmux/init.tmux
%hidden plugin="$HOME/.config/tmux/plugins"
source $plugin/misty.tmux/init.tmux


