# ALACRITTY config,


[keyboard]
bindings = [

{key= "Copy",                   action= "Copy"  },
{key= "Paste",                  action= "Paste" },

# {key= "V",     mods= "Control", action= "Paste" },

]


