# FCITX config,


# Theme=misty
# DarkTheme=misty
Theme=misty-orange
DarkTheme=misty-orange

PreferTextIcon=True
ShowLayoutNameInIcon=True
UseInputMethodLanguageToDisplayText=True

# Font="Sans 12"
# MenuFont="Sans 12"
# TrayFont="Sans Bold 12"
Font="JetBrainsMono Nerd Font 16"
MenuFont="JetBrainsMono Nerd Font 16"
TrayFont="JetBrainsMono Nerd Font Bold 12"

TrayTextColor=#d0ffa0
TrayOutlineColor=#002020

Vertical Candidate List=False
WheelForPaging=True

UseDarkTheme=False
UseAccentColor=True
PerScreenDPI=False
EnableFractionalScale=True
ForceWaylandDPI=0


